/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 volkswagen_golf1.glb 
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { Select } from "@react-three/postprocessing";
import { useControls, folder } from "leva";

export function VolkswagenCanvas({ config, setConfig ,setSelectedElements,selectedElements}) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/volkswagen_golf1.glb");
  const [hovered, hover] = useState();

  // const config = useControls({
  //   all: { value: false },
  //   parts: folder(
  //     {
  //       front_bumper: { value: false }
  //       hood: { value: false },
  //       back_bumper: { value: true },
  //       front_fender_left: {value: false},
  //       front_fender_rigth: {value: false},
  //       roof:{value: false},
  //       front_door_left:{value: false},
  //       front_door_rigth:{value: false},
  //       back_door_left:{value: false},
  //       back_door_rigth:{value: false},
  //       trunk_lid:{value: false},
  //       back_fender_left: {value: false},
  //       back_fender_rigth: {value: false},
  //     },
  //     { collapsed: true },
  //   ),
  // })

  return (
    <group
      onClick={(e) => {
        e.stopPropagation();
        setConfig({
          ...config,
          [e.object.parent.name]: !config[e.object.parent.name],
        });
        config[e.object.parent.name]  ? setSelectedElements(selectedElements.filter((item)=> item.name !== e.object.parent.name))  : setSelectedElements([...selectedElements,{"name": e.object.parent.name}] )
        console.log(
          e.object.parent.name,
          config, 
          !config[e.object.parent.name]
        );
      }}
    >
      <Select enabled={config.all}>
        <group dispose={null}>
          <group
            position={[0, 2.283, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.1}
          >
            <group
              position={[0, -57.052, 27.28]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <mesh
                geometry={nodes.Object_284.geometry}
                material={materials.Piano_Black}
                position={[-142.608, 298.666, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              />
            </group>
            <group
              position={[0, 25.945, 6.337]}
              rotation={[0, -1.571, 0]}
              scale={0.238}
            >
              <mesh
                geometry={nodes.Object_231.geometry}
                material={materials.Interiors}
                position={[-57.784, -206.517, 146.767]}
                rotation={[0, 1.571, 0]}
                scale={4.201}
              />
            </group>
            <group
              position={[0, -9.95, -3.238]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[17.166, 52.064, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <Select
                  name="front_door_left"
                  enabled={
                    hovered === "front_door_left" || config.front_door_left
                  }
                >
                  <mesh
                    geometry={nodes.Object_356.geometry}
                    material={materials.Car_Paint}
                    position={[-24.192, 111.341, 13.381]}
                  />
                </Select>
                <Select
                  name="back_door_left"
                  enabled={
                    hovered === "back_door_left" || config.back_door_left
                  }
                >
                  <mesh
                    geometry={nodes.Object_356001.geometry}
                    material={materials.Car_Paint}
                    position={[8.62, -132.96, -6.079]}
                  />
                  =
                </Select>
                <Select
                  name="back_door_rigth"
                  enabled={
                    hovered === "back_door_rigth" || config.back_door_rigth
                  }
                >
                  <mesh
                    geometry={nodes.Object_356002.geometry}
                    material={materials.Car_Paint}
                    position={[0.661, 58.896, 22.87]}
                  />
                </Select>
                <Select
                  name="front_door_rigth"
                  enabled={
                    hovered === "front_door_rigth" || config.front_door_rigth
                  }
                >
                  <mesh
                    geometry={nodes.Object_356003.geometry}
                    material={materials.Car_Paint}
                    position={[-24.272, 126.569, 13.381]}
                  />
                </Select>
                <mesh
                  geometry={nodes.Object_358.geometry}
                  material={materials.Pure_Black}
                />
              </group>
            </group>
            <group position={[0, 69.877, -14.845]}>
              <group position={[-29.284, -69.936, 14.998]}>
                <mesh
                  geometry={nodes.Object_161.geometry}
                  material={materials.Plastic}
                />
                <mesh
                  geometry={nodes.Object_163.geometry}
                  material={materials.Glass_Clear}
                />
                <mesh
                  geometry={nodes.Object_165.geometry}
                  material={materials.Chrome}
                />
              </group>
            </group>

            <group
              position={[0, 69.465, -11.79]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[61.943, -363.716, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <Select
                  name="front_bumper"
                  enabled={hovered === "front_bumper" || config.front_bumper}
                >
                  <mesh
                    geometry={nodes.Object_153.geometry}
                    material={materials.Car_Paint}
                  />
                  <mesh
                    geometry={nodes.Object_155.geometry}
                    material={materials.Plastic}
                  />
                  <mesh
                    geometry={nodes.Object_157.geometry}
                    material={materials.Pure_Black}
                  />
                </Select>
              </group>
            </group>

            <group
              position={[0, 73.775, -15.151]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[79.538, -385.958, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <mesh
                  geometry={nodes.Object_193.geometry}
                  material={materials.Plastic}
                />
                <mesh
                  geometry={nodes.Object_195.geometry}
                  material={materials.Chrome}
                />
              </group>
            </group>
            <group
              position={[0, 48.184, -3.105]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[16.471, -252.295, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <Select
                  name="front_fender_left"
                  enabled={
                    hovered === "front_fender_left" || config.front_fender_left
                  }
                >
                  <mesh
                    geometry={nodes.Object_366.geometry}
                    material={materials.Car_Paint}
                    position={[13.5, 59.996, -5.3]}
                  />
                </Select>
                <Select
                  name="front_fender_rigth"
                  enabled={
                    hovered === "front_fender_rigth" ||
                    config.front_fender_rigth
                  }
                >
                  <mesh
                    geometry={nodes.Object_366001.geometry}
                    material={materials.Car_Paint}
                    position={[13.5, 59.996, -5.3]}
                  />
                </Select>
              </group>
            </group>
            <group
              position={[0, 74.844, -9.883]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[51.954, -391.873, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <mesh
                  geometry={nodes.Object_314.geometry}
                  material={materials.Chrome}
                />
                <mesh
                  geometry={nodes.Object_316.geometry}
                  material={materials.Pure_Black}
                />
                <mesh
                  geometry={nodes.Object_318.geometry}
                  material={materials.Plastic}
                />
              </group>
            </group>
            <group position={[-0.008, 82.376, -9.911]} scale={0.987}>
              <group position={[0.009, -83.475, 10.042]} scale={1.013}>
                <mesh
                  geometry={nodes.Object_213.geometry}
                  material={materials.Yellow}
                />
                <mesh
                  geometry={nodes.Object_215.geometry}
                  material={materials.Blue}
                />
                <mesh
                  geometry={nodes.Object_217.geometry}
                  material={materials.White}
                />
                <mesh
                  geometry={nodes.Object_219.geometry}
                  material={materials.Black}
                />
                <mesh
                  geometry={nodes.Object_221.geometry}
                  material={materials.Chrome2}
                />
                <mesh
                  geometry={nodes.Object_223.geometry}
                  material={materials.City_Badge}
                />
              </group>
            </group>
            <group
              position={[0, 79.045, -2.989]}
              rotation={[2.055, 0, Math.PI]}
              scale={[-0.184, -0.194, -0.152]}
            >
              <group
                position={[-0.624, 252.827, -480.385]}
                rotation={[2.054, 0, -Math.PI]}
                scale={[-5.444, -6.569, -5.162]}
              >
                <mesh
                  geometry={nodes.Object_328.geometry}
                  material={materials.Piano_Black}
                />
                <mesh
                  geometry={nodes.Object_330.geometry}
                  material={materials.Chrome}
                />
              </group>
            </group>
            <group
              position={[30.448, -57.783, 7.237]}
              rotation={[2.837, -1.557, 2.837]}
              scale={0.382}
            >
              <mesh
                geometry={nodes.Object_235.geometry}
                material={materials.Pure_Black}
                position={[-36.634, 302.821, 251.974]}
                rotation={[3.137, 1.558, Math.PI]}
                scale={2.618}
              />
            </group>
            <group
              position={[-16.436, -78.66, 0.603]}
              rotation={[Math.PI / 2, -0.209, 0]}
              scale={[0.053, 0.049, 0.049]}
            >
              <mesh
                geometry={nodes.Object_288.geometry}
                material={materials.Chrome}
                position={[-35.055, -20.186, -1636.343]}
                rotation={[-Math.PI / 2, 0, 0.209]}
                scale={[18.896, 20.481, 20.481]}
              />
            </group>
            <group
              position={[0, 70.963, -1.958]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <mesh
                geometry={nodes.Object_169.geometry}
                material={materials.Glass_Clear}
                position={[10.465, -371.555, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              />
            </group>
            <group
              position={[0, 65.889, -1.967]}
              rotation={[0, -1.571, 0]}
              scale={[0.382, 0.382, 0.354]}
            >
              <group
                position={[10.157, -345.037, 94.189]}
                rotation={[0, 1.571, 0]}
                scale={[2.828, 2.618, 2.618]}
              >
                <mesh
                  geometry={nodes.Object_173.geometry}
                  material={materials.Pure_Black}
                />
                <mesh
                  geometry={nodes.Object_175.geometry}
                  material={materials.Piano_Black}
                />
                <mesh
                  geometry={nodes.Object_177.geometry}
                  material={materials.Plastic}
                />
                <mesh
                  geometry={nodes.Object_179.geometry}
                  material={materials.Plastic}
                />
                <mesh
                  geometry={nodes.Object_181.geometry}
                  material={materials.Chrome}
                />
                <mesh
                  geometry={nodes.Object_183.geometry}
                  material={materials.Aluminum}
                />
                <mesh
                  geometry={nodes.Object_185.geometry}
                  material={materials.Solid_Glass}
                />
                <mesh
                  geometry={nodes.Object_187.geometry}
                  material={materials.White_Paint}
                />
                <mesh
                  geometry={nodes.Object_189.geometry}
                  material={materials.White_Paint}
                />
              </group>
            </group>

            <group
              position={[0, 57.338, 4.248]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[-22.025, -300.22, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <Select name="hood" enabled={hovered === "hood" || config.hood}>
                  <mesh
                    geometry={nodes.Object_370.geometry}
                    material={materials.Car_Paint}
                  />
                  <mesh
                    geometry={nodes.Object_372.geometry}
                    material={materials.Pure_Black}
                  />
                </Select>
              </group>
            </group>

            <group
              position={[0, -17.736, 3.307]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <mesh
                geometry={nodes.Object_362.geometry}
                material={materials.Interiors}
                position={[-17.098, 92.826, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              />
            </group>
            <group
              position={[-0.29, 20.382, 10.357]}
              rotation={[Math.PI / 2, 0.299, 0]}
              scale={[0.057, 0.063, 0.073]}
            >
              <group
                position={[-588.537, -159.774, 467.217]}
                rotation={[-1.579, -0.018, -0.297]}
                scale={[17.647, 13.779, 15.969]}
              >
                <mesh
                  geometry={nodes.Object_300.geometry}
                  material={materials.Glass_Clear}
                />
                <mesh
                  geometry={nodes.Object_302.geometry}
                  material={materials.Chrome}
                />
              </group>
            </group>
            <group
              position={[0, 2.732, -11.592]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={0.066}
            >
              <mesh
                geometry={nodes.Object_276.geometry}
                material={materials.Plastic}
                position={[893.61, 114.56, 337.712]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={15.256}
              />
            </group>
            <group position={[-27.017, -74.338, -11.271]}>
              <mesh
                geometry={nodes.Object_119.geometry}
                material={materials.Rear_Reflectors}
                position={[24.614, 58.486, 22.542]}
              />
            </group>

            <group position={[0, -72.018, -7.698]}>
              <group position={[-29.42, 53.845, 15.397]}>
                <Select
                  name="back_bumper"
                  enabled={hovered === "back_bumper" || config.back_bumper}
                >
                  <mesh
                    geometry={nodes.Object_129.geometry}
                    material={materials.Car_Paint}
                  />
                  <mesh
                    geometry={nodes.Object_131.geometry}
                    material={materials.Pure_Black}
                  />
                </Select>
              </group>
            </group>

            <group position={[0.005, -76.46, -15.726]}>
              <group position={[-29.425, 62.736, 31.452]}>
                <mesh
                  geometry={nodes.Object_123.geometry}
                  material={materials.Plastic}
                />
                <mesh
                  geometry={nodes.Object_125.geometry}
                  material={materials.Chrome}
                />
              </group>
            </group>
            <group
              position={[0, -16.233, 3.384]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[-17.5, 84.961, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <Select
                  name="back_fender_left"
                  enabled={
                    hovered === "back_fender_left" || config.back_fender_left
                  }
                >
                  <mesh
                    geometry={nodes.Object_376.geometry}
                    material={materials.Car_Paint}
                  />
                </Select>
                <Select
                  name="back_fender_rigth"
                  enabled={
                    hovered === "back_fender_rigth" || config.back_fender_rigth
                  }
                >
                  <mesh
                    geometry={nodes.Object_376001.geometry}
                    material={materials.Car_Paint}
                  />
                </Select>
                <mesh
                  geometry={nodes.Object_378.geometry}
                  material={materials.Pure_Black}
                />
              </group>
            </group>
            <group
              position={[-0.008, -81.555, -8.856]}
              rotation={[-0.24, 0, Math.PI]}
              scale={0.987}
            >
              <group
                position={[-0.009, -78.153, 28.326]}
                rotation={[-0.24, 0, -Math.PI]}
                scale={1.013}
              >
                <mesh
                  geometry={nodes.Object_199.geometry}
                  material={materials.Yellow}
                />
                <mesh
                  geometry={nodes.Object_201.geometry}
                  material={materials.Blue}
                />
                <mesh
                  geometry={nodes.Object_203.geometry}
                  material={materials.White}
                />
                <mesh
                  geometry={nodes.Object_205.geometry}
                  material={materials.Black}
                />
                <mesh
                  geometry={nodes.Object_207.geometry}
                  material={materials.Chrome2}
                />
                <mesh
                  geometry={nodes.Object_209.geometry}
                  material={materials.City_Badge}
                />
              </group>
            </group>
            <group
              position={[0, -79.818, 5.645]}
              rotation={[-1.832, 0, 0]}
              scale={[-0.158, -0.167, -0.131]}
            >
              <group
                position={[-0.624, 150.732, -614.508]}
                rotation={[1.827, 0, 0]}
                scale={[-6.333, -7.552, -6.116]}
              >
                <mesh
                  geometry={nodes.Object_322.geometry}
                  material={materials.Piano_Black}
                  position={[0, 0.321, -5.523]}
                />
                <mesh
                  geometry={nodes.Object_324.geometry}
                  material={materials.Chrome}
                  position={[0, 0.312, -5.378]}
                />
              </group>
            </group>

            <group
              position={[0, -24.758, 26.021]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <Select name="roof" enabled={hovered === "roof" || config.roof}>
                <mesh
                  geometry={nodes.Object_344.geometry}
                  material={materials.Car_Paint}
                  position={[-136.016, 129.592, 93.01]}
                  rotation={[0, 1.571, 0]}
                  scale={2.618}
                />
              </Select>
            </group>

            <group position={[0, -20.721, 1.745]} scale={[1.015, 0.916, 0.916]}>
              <mesh
                geometry={nodes.Object_227.geometry}
                material={materials.Interiors}
                position={[106.241, 44.975, -6.275]}
                scale={[0.985, 1.091, 1.091]}
              />
            </group>
            <group
              position={[0, -9.731, 16.624]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[-86.823, 50.915, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <mesh
                  geometry={nodes.Object_338.geometry}
                  material={materials.Piano_Black}
                />
                <mesh
                  geometry={nodes.Object_340.geometry}
                  material={materials.Plastic}
                />
              </group>
            </group>
            <group
              position={[0, -63.601, 24.23]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <mesh
                geometry={nodes.Object_352.geometry}
                material={materials.Car_Paint}
                position={[-126.642, 332.953, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              />
            </group>
            <group
              position={[0, -65.92, 23.965]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <mesh
                geometry={nodes.Object_334.geometry}
                material={materials.Stop_Light}
                position={[-125.253, 345.093, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              />
            </group>
            <group
              position={[0, -71.731, 5.962]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[-30.999, 375.35, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <mesh
                  geometry={nodes.Object_292.geometry}
                  material={materials.Glass_Clear1}
                />
                <mesh
                  geometry={nodes.Object_294.geometry}
                  material={materials.GlassRed}
                />
                <mesh
                  geometry={nodes.Object_296.geometry}
                  material={materials.Dark_Red}
                />
              </group>
            </group>
            <group
              position={[0, -70.78, 5.931]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[-30.838, 370.54, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <mesh
                  geometry={nodes.Object_135.geometry}
                  material={materials.Piano_Black}
                />
                <mesh
                  geometry={nodes.Object_137.geometry}
                  material={materials.Dark_Red}
                />
                <mesh
                  geometry={nodes.Object_139.geometry}
                  material={materials.Glass_Clear1}
                />
                <mesh
                  geometry={nodes.Object_141.geometry}
                  material={materials.material}
                />
                <mesh
                  geometry={nodes.Object_143.geometry}
                  material={materials.Light_Red}
                />
                <mesh
                  geometry={nodes.Object_145.geometry}
                  material={materials.Chrome1}
                />
                <mesh
                  geometry={nodes.Object_147.geometry}
                  material={materials.Chrome1}
                />
                <mesh
                  geometry={nodes.Object_149.geometry}
                  material={materials.Aluminium}
                />
              </group>
            </group>
            <group
              position={[0, -75.009, 3.388]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <Select
                name="trunk_lid"
                enabled={hovered === "trunk_lid" || config.trunk_lid}
              >
                <mesh
                  geometry={nodes.Object_348.geometry}
                  material={materials.Car_Paint}
                  position={[-17.523, 392.679, 93.01]}
                  rotation={[0, 1.571, 0]}
                  scale={2.618}
                />
              </Select>
            </group>
            <group
              position={[29.25, 49.248, -15.61]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.069, 0.067, 0.067]}
            >
              <group
                position={[-31.251, 0, 0]}
                rotation={[0.853, -Math.PI / 2, 0]}
                scale={[0.434, 0.434, 0.414]}
              >
                <group
                  position={[-921.239, 1502.864, -1233.011]}
                  rotation={[-Math.PI / 2, 0.718, -Math.PI / 2]}
                  scale={[34.884, 34.143, 34.143]}
                >
                  <mesh
                    geometry={nodes.Object_95.geometry}
                    material={materials.Brake_Disc}
                  />
                  <mesh
                    geometry={nodes.Object_97.geometry}
                    material={materials.Black_Paint}
                  />
                </group>
              </group>
              <group
                position={[-66.977, 0.02, 0.037]}
                rotation={[-1.134, -Math.PI / 2, 0]}
                scale={[0.284, 0.257, 0.271]}
              >
                <group
                  position={[2961.881, -685.859, -1887.456]}
                  rotation={[1.579, 0.088, 1.561]}
                  scale={[53.314, 52.331, 57.697]}
                >
                  <mesh
                    geometry={nodes.Object_113.geometry}
                    material={materials.Plastic}
                  />
                  <mesh
                    geometry={nodes.Object_115.geometry}
                    material={materials.Caliper_Paint}
                  />
                </group>
              </group>
              <group
                position={[-52.327, 0, -53.768]}
                rotation={[-Math.PI, 1.471, 1.571]}
                scale={[-1.314, -1.386, -1.089]}
              >
                <group
                  position={[555.394, 330.372, -442.168]}
                  rotation={[1.671, 0.088, -1.652]}
                  scale={[-12.851, -11.29, -11.22]}
                >
                  <mesh
                    geometry={nodes.Object_87.geometry}
                    material={materials.Piano_Black}
                    position={[-1.353, 4.866, 1.172]}
                  />
                  <mesh
                    geometry={nodes.Object_89.geometry}
                    material={materials.Plastic}
                    position={[-3.07, 4.819, 0.552]}
                  />
                  <mesh
                    geometry={nodes.Object_91.geometry}
                    material={materials.Chrome}
                    position={[-2.227, 4.3, 0.353]}
                  />
                </group>
              </group>
              <group
                position={[-66.977, 0.02, 0.037]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[4.544, 4.544, 4.424]}
              >
                <mesh
                  geometry={nodes.Object_83.geometry}
                  material={materials.Aluminum}
                  position={[-160.74, 50.942, -110.612]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={3.264}
                />
              </group>
              <group
                position={[0.392, 0, 0]}
                rotation={[0, 0, Math.PI]}
                scale={[0.456, 0.341, 0.341]}
              >
                <group
                  position={[-1181.71, -2045.078, 1223.718]}
                  scale={[31.667, 43.548, 43.548]}
                >
                  <mesh
                    geometry={nodes.Object_101.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_103.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_105.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_107.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_109.geometry}
                    material={materials.Sidewall}
                  />
                </group>
              </group>
            </group>
            <group
              position={[-29.25, 49.248, -15.61]}
              scale={[0.069, 0.067, 0.067]}
            >
              <group
                position={[-31.251, 0, 0]}
                rotation={[0.853, -Math.PI / 2, 0]}
                scale={[0.434, 0.434, 0.414]}
              >
                <group
                  position={[1612.217, -708.714, -1233.009]}
                  rotation={[-Math.PI / 2, 0.718, Math.PI / 2]}
                  scale={[34.884, 34.143, 34.143]}
                >
                  <mesh
                    geometry={nodes.Object_248.geometry}
                    material={materials.Brake_Disc}
                  />
                  <mesh
                    geometry={nodes.Object_250.geometry}
                    material={materials.Black_Paint}
                  />
                </group>
              </group>
              <group
                position={[-28.768, -71.619, 12.175]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.284, 0.257, 0.271]}
              >
                <group
                  position={[2518.302, -149.038, -1605.274]}
                  rotation={[-1.595, 0.35, 1.611]}
                  scale={[53.314, 52.954, 57.126]}
                >
                  <mesh
                    geometry={nodes.Object_270.geometry}
                    material={materials.Plastic}
                    position={[2.513, -0.081, 0.052]}
                  />
                  <mesh
                    geometry={nodes.Object_272.geometry}
                    material={materials.Caliper_Paint}
                    position={[2.085, -0.067, 0.043]}
                  />
                </group>
              </group>
              <group
                position={[-52.327, 0, -53.768]}
                rotation={[-Math.PI, 1.471, 1.571]}
                scale={[-1.314, -1.386, -1.089]}
              >
                <group
                  position={[-556.643, 330.372, -442.167]}
                  rotation={[1.671, 0.088, 1.49]}
                  scale={[-12.851, -11.29, -11.22]}
                >
                  <mesh
                    geometry={nodes.Object_240.geometry}
                    material={materials.Piano_Black}
                    position={[-5.017, -5.681, -7.812]}
                  />
                  <mesh
                    geometry={nodes.Object_242.geometry}
                    material={materials.Plastic}
                  />
                  <mesh
                    geometry={nodes.Object_244.geometry}
                    material={materials.Chrome}
                  />
                </group>
              </group>
              <group
                position={[-66.978, 0.021, 0.037]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[4.544, 4.544, 4.424]}
              >
                <mesh
                  geometry={nodes.Object_266.geometry}
                  material={materials.Aluminum}
                  position={[160.749, 50.942, -110.612]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={3.264}
                />
              </group>
              <group
                position={[0.392, 0, 0]}
                rotation={[0, 0, Math.PI]}
                scale={[0.456, 0.341, 0.341]}
              >
                <group
                  position={[-1181.711, 2244.314, 1223.718]}
                  rotation={[0, 0, -Math.PI]}
                  scale={[31.667, 43.548, 43.548]}
                >
                  <mesh
                    geometry={nodes.Object_254.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_256.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_258.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_260.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_262.geometry}
                    material={materials.Sidewall}
                  />
                </group>
              </group>
            </group>
            <group
              position={[29.25, -53.411, -15.61]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.069, 0.067, 0.067]}
            >
              <group
                position={[-31.251, 0, 0]}
                rotation={[0.853, -Math.PI / 2, 0]}
                scale={[0.434, 0.434, 0.414]}
              >
                <group
                  position={[1719.276, -802.169, -1233.008]}
                  rotation={[-Math.PI / 2, 0.718, -Math.PI / 2]}
                  scale={[34.884, 34.143, 34.143]}
                >
                  <mesh
                    geometry={nodes.Object_27.geometry}
                    material={materials.Brake_Disc}
                  />
                  <mesh
                    geometry={nodes.Object_29.geometry}
                    material={materials.Black_Paint}
                  />
                </group>
              </group>
              <group
                position={[-66.978, 0.02, 0.037]}
                rotation={[-1.134, -Math.PI / 2, 0]}
                scale={[0.284, 0.257, 0.271]}
              >
                <group
                  position={[-2385.484, -1202.447, -1887.456]}
                  rotation={[1.579, 0.088, 1.561]}
                  scale={[53.314, 52.331, 57.697]}
                >
                  <mesh
                    geometry={nodes.Object_9.geometry}
                    material={materials.Plastic}
                  />
                  <mesh
                    geometry={nodes.Object_11.geometry}
                    material={materials.Caliper_Paint}
                  />
                </group>
              </group>
              <group
                position={[-52.327, 0, -53.768]}
                rotation={[-Math.PI, 1.471, 1.571]}
                scale={[-1.314, -1.386, -1.089]}
              >
                <group
                  position={[-603.635, 330.372, -442.167]}
                  rotation={[1.671, 0.088, -1.652]}
                  scale={[-12.851, -11.29, -11.22]}
                >
                  <mesh
                    geometry={nodes.Object_17.geometry}
                    material={materials.Plastic}
                  />
                  <mesh
                    geometry={nodes.Object_19.geometry}
                    material={materials.Chrome}
                  />
                  <mesh
                    geometry={nodes.Object_15.geometry}
                    material={materials.Piano_Black}
                  />
                </group>
              </group>
              <group
                position={[-66.978, 0.02, 0.037]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[4.544, 4.544, 4.424]}
              >
                <mesh
                  geometry={nodes.Object_23.geometry}
                  material={materials.Aluminum}
                  position={[174.335, 50.942, -110.612]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={3.264}
                />
              </group>
              <group
                position={[0.392, 0, 0]}
                rotation={[0, 0, Math.PI]}
                scale={[0.456, 0.341, 0.341]}
              >
                <group
                  position={[-1181.71, 2425.573, 1223.718]}
                  scale={[31.667, 43.548, 43.548]}
                >
                  <mesh
                    geometry={nodes.Object_33.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_35.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_37.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_39.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_41.geometry}
                    material={materials.Sidewall}
                  />
                </group>
              </group>
            </group>
            <group
              position={[-29.25, -53.411, -15.61]}
              scale={[0.069, 0.067, 0.067]}
            >
              <group
                position={[-31.251, 0, 0]}
                rotation={[0.853, -Math.PI / 2, 0]}
                scale={[0.434, 0.434, 0.414]}
              >
                <group
                  position={[-1028.297, 1596.32, -1233.011]}
                  rotation={[-Math.PI / 2, 0.718, Math.PI / 2]}
                  scale={[34.884, 34.143, 34.143]}
                >
                  <mesh
                    geometry={nodes.Object_58.geometry}
                    material={materials.Brake_Disc}
                  />
                  <mesh
                    geometry={nodes.Object_60.geometry}
                    material={materials.Black_Paint}
                  />
                </group>
              </group>
              <group
                position={[-28.768, -71.62, 12.175]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.284, 0.257, 0.271]}
              >
                <group
                  position={[-2525.77, 1878.175, -1605.273]}
                  rotation={[-1.595, 0.35, 1.611]}
                  scale={[53.314, 52.954, 57.126]}
                >
                  <mesh
                    geometry={nodes.Object_76.geometry}
                    material={materials.Plastic}
                  />
                  <mesh
                    geometry={nodes.Object_78.geometry}
                    material={materials.Caliper_Paint}
                  />
                </group>
              </group>
              <group
                position={[-52.327, 0, -53.768]}
                rotation={[-Math.PI, 1.471, 1.571]}
                scale={[-1.314, -1.386, -1.089]}
              >
                <group
                  position={[602.386, 330.372, -442.167]}
                  rotation={[1.671, 0.088, 1.49]}
                  scale={[-12.851, -11.29, -11.22]}
                >
                  <mesh
                    geometry={nodes.Object_64.geometry}
                    material={materials.Piano_Black}
                    position={[2.443, -4.791, 1.515]}
                  />
                  <mesh
                    geometry={nodes.Object_66.geometry}
                    material={materials.Plastic}
                    position={[2.308, -4.836, 1.451]}
                  />
                  <mesh
                    geometry={nodes.Object_68.geometry}
                    material={materials.Chrome}
                    position={[2.29, -4.845, 1.371]}
                  />
                </group>
              </group>
              <group
                position={[-66.978, 0.02, 0.037]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[4.544, 4.544, 4.424]}
              >
                <mesh
                  geometry={nodes.Object_72.geometry}
                  material={materials.Aluminum}
                  position={[-174.326, 50.942, -110.612]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={3.264}
                />
              </group>
              <group
                position={[0.392, 0, 0]}
                rotation={[0, 0, Math.PI]}
                scale={[0.456, 0.341, 0.341]}
              >
                <group
                  position={[-1181.71, -2226.336, 1223.718]}
                  rotation={[0, 0, -Math.PI]}
                  scale={[31.667, 43.548, 43.548]}
                >
                  <mesh
                    geometry={nodes.Object_46.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_48.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_50.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_52.geometry}
                    material={materials.Tire_Tread}
                  />
                  <mesh
                    geometry={nodes.Object_54.geometry}
                    material={materials.Sidewall}
                  />
                </group>
              </group>
            </group>
            <group
              position={[0, -17.027, 16.554]}
              rotation={[0, -1.571, 0]}
              scale={0.382}
            >
              <group
                position={[-86.455, 89.115, 93.01]}
                rotation={[0, 1.571, 0]}
                scale={2.618}
              >
                <mesh
                  geometry={nodes.Object_382.geometry}
                  material={materials.Piano_Black}
                />
                <mesh
                  geometry={nodes.Object_384.geometry}
                  material={materials.Glass_Tinted}
                />
              </group>
            </group>
            <group
              position={[-0.386, 20.777, 9.826]}
              rotation={[Math.PI / 2, 0.299, 0]}
              scale={[0.057, 0.063, 0.073]}
            >
              <group
                position={[-588.284, -142.822, 478.734]}
                rotation={[-1.579, -0.018, -0.297]}
                scale={[17.647, 13.779, 15.969]}
              >
                <mesh
                  geometry={nodes.Object_306.geometry}
                  material={materials.Car_Paint}
                />
                <mesh
                  geometry={nodes.Object_308.geometry}
                  material={materials.Plastic}
                />
                <mesh
                  geometry={nodes.Object_310.geometry}
                  material={materials.Chrome}
                />
              </group>
            </group>
            <group
              position={[9.678, -14.398, 10.543]}
              rotation={[0.795, 0.075, 0.151]}
              scale={[0.082, 0.077, 0.052]}
            >
              <group
                position={[-367.47, -330.328, 376.918]}
                rotation={[-0.113, 0.001, 0.03]}
                scale={[12.124, 13.093, 19.079]}
              >
                <mesh
                  geometry={nodes.Object_280.geometry}
                  material={materials.Plastic}
                  position={[-2.045, 6.49, -11.02]}
                />
              </group>
            </group>
          </group>
        </group>
      </Select>
    </group>
  );
}

useGLTF.preload("/volkswagen_golf1.glb");
